# Generated by Django 6.0.5 on 2026-06-02 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='short_description',
        ),
    ]
